#!/usr/bin/env python
"""
Benchmrk for uploading files using requests.
"""

import io
import sys

import requests

from six.moves.urllib.parse import urlunparse

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

import bench
import util


class RequestsIterator(util.BlockIterator):
    """
    Ugly hacks for requests.
    """

    def __init__(self, reader, blocksize, size):
        super(RequestsIterator, self).__init__(reader, blocksize)
        # Needed by requests to use indentity transfer encoding.
        self.len = size

    if sys.version_info[0] == 2:
        # In python 2 HTTPConnection.send() will try to use a read() method. In
        # python 3, if we don't have a read method, it will try to iterate over
        # the object.
        def read(self, n):
            return self._reader.read(n)


def upload(filename, offset, size, url, blocksize):
    with io.open(filename, "rb") as f:
        f.seek(offset)
        f = util.LimitedReader(f, size)
        f = RequestsIterator(f, blocksize, size)
        url = urlunparse(url)

        headers = {
            "Content-Length": str(size),
            "Content-Range": "bytes %d-%d/*" % (offset, offset + size - 1),
        }
        # verify=False to disable certificate verification.
        resp = requests.put(url, data=f, headers=headers, verify=False)

    assert resp.status_code == 200


with bench.run() as args:
    util.parallel(upload, args)
